export const frenchCities = [
  "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille",
  "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne",
  "Le Mans", "Aix-en-Provence", "Clermont-Ferrand", "Brest", "Tours", "Amiens", "Limoges", "Annecy", "Perpignan",
  "Boulogne-Billancourt", "Metz", "Besançon", "Orléans", "Mulhouse", "Rouen", "Caen", "Nancy", "Argenteuil",
  "Montreuil", "Saint-Denis", "Roubaix", "Tourcoing", "Avignon", "Poitiers", "Nanterre", "Créteil", "Versailles",
  "Pau", "Courbevoie", "Vitry-sur-Seine", "Colombes", "Aulnay-sous-Bois", "Asnières-sur-Seine", "Rueil-Malmaison",
  "Antibes", "Saint-Maur-des-Fossés", "Champigny-sur-Marne", "La Rochelle", "Aubervilliers", "Calais", "Cannes",
  "Béziers", "Colmar", "Bourges", "Dunkerque", "Mérignac", "Saint-Nazaire", "Valence", "Ajaccio",
  "Issy-les-Moulineaux", "Levallois-Perret", "Quimper", "Cergy", "Villeneuve-d'Ascq", "Troyes", "Niort", "Lorient",
  "Chambéry", "Montauban", "Saint-Quentin", "Pessac", "Ivry-sur-Seine", "Clichy", "Neuilly-sur-Seine", "Vénissieux",
  "Beauvais", "Cholet", "Hyères", "La Seyne-sur-Mer", "Arles", "Bondy", "Clamart", "Épinay-sur-Seine", "Meaux",
  "Fréjus", "Narbonne", "Grasse", "Villejuif", "Vincennes", "Saint-Malo", "Châteauroux", "Vannes", "Sarcelles",
  "Maisons-Alfort", "Pantin", "Évreux", "Bayonne", "Sevran", "Garges-lès-Gonesse", "Saint-Priest", "Laval",
  "Noisy-le-Grand", "Drancy", "Antony", "Saint-Ouen-sur-Seine", "Suresnes", "Cagnes-sur-Mer", "Blois",
  "Fontenay-sous-Bois", "Belfort", "Charleville-Mézières", "Châlons-en-Champagne", "Bobigny", "Livry-Gargan",
  "Massy", "Saint-Brieuc", "Rosny-sous-Bois", "Corbeil-Essonnes", "Compiègne", "Évry", "Neuilly-sur-Marne",
  "Vaulx-en-Velin", "Brive-la-Gaillarde", "Colomiers", "La Courneuve", "Thionville", "Choisy-le-Roi", "Valenton",
  "Viry-Châtillon", "Montluçon", "Albi", "Tarbes", "Villefranche-sur-Saône", "Stains", "Alfortville", "Gennevilliers",
  "Martigues", "Talence", "Angoulême", "Vitrolles", "Le Blanc-Mesnil", "Wattrelos", "Douai", "Dole", "Saint-Germain-en-Laye",
  "Bourg-en-Bresse", "Castres", "Arras", "Valenciennes", "Montrouge", "La Roche-sur-Yon", "Puteaux", "Sartrouville",
  "Istres", "Cayenne", "Salon-de-Provence", "Saint-Herblain", "Châtenay-Malabry", "Chartres", "Villepinte",
  "Le Cannet", "Poissy", "Bagnolet", "Saint-Laurent-du-Var", "Thonon-les-Bains", "Épinal", "Caluire-et-Cuire",
  "Bron", "Lens", "Garges-lès-Gonesse", "Chelles", "Savigny-sur-Orge", "Gagny", "Carcassonne", "Gap",
  "Chalon-sur-Saône", "Saint-Martin-d'Hères", "Mâcon", "Nevers", "Montbéliard", "Rezé", "Saint-André-lez-Lille",
  "Pontault-Combault", "Conflans-Sainte-Honorine", "Thiais", "Montigny-le-Bretonneux", "Auxerre", "Haguenau",
  "Corbeil-Essonnes", "Villeneuve-Saint-Georges", "Mantes-la-Jolie", "Les Mureaux", "Alès", "Vienne",
  "Le Kremlin-Bicêtre", "Les Lilas", "Romainville", "Nogent-sur-Marne", "Villenave-d'Ornon", "Périgueux",
  "Sainte-Geneviève-des-Bois", "Bagneux", "Saint-Chamond", "Savigny-le-Temple", "Draguignan", "Six-Fours-les-Plages",
  "Agen", "Montélimar", "Châtellerault", "Sète", "Roanne", "Schiltigheim", "Saint-Leu-la-Forêt", "Athis-Mons",
  "Villemomble", "Franconville", "Meyzieu", "Pierrefitte-sur-Seine", "Goussainville", "Sotteville-lès-Rouen",
  "Malakoff", "Trappes", "Bezons", "Épinay-sur-Seine", "Bois-Colombes", "Grigny", "Noisy-le-Sec", "Stains",
  "Tremblay-en-France", "La Ciotat", "Fresnes", "Le Perreux-sur-Marne", "Houilles", "Rillieux-la-Pape",
  "Le Chesnay", "Fontenay-aux-Roses", "Châtillon", "Bagnolet", "Villiers-sur-Marne", "Draveil", "Pontoise",
  "Carpentras", "Ris-Orangis", "Saint-Dizier", "Maubeuge", "Montrouge", "Cambrai", "Orange", "Saumur",
  "Villiers-le-Bel", "Romilly-sur-Seine", "Mâcon", "Montluçon", "Vierzon", "Aurillac", "Soissons", "Melun",
  "Tarbes", "Liévin", "Saint-Benoît", "Bergerac", "Biarritz", "Menton", "Lunéville", "Yutz", "Villeneuve-la-Garenne",
  "Orvault", "Dammarie-les-Lys", "Creil", "Saint-Médard-en-Jalles", "Olivet", "Forbach", "Montigny-lès-Metz",
  "Bruay-la-Buissière", "Le Pontet", "Hénin-Beaumont", "Montgeron", "Calvi", "Bastia", "Porto-Vecchio",
  "Saint-Martin", "Fort-de-France", "Pointe-à-Pitre", "Mamoudzou", "Saint-Pierre", "Saint-Paul",
  "Nouméa", "Papeete", "Le Tampon", "Saint-André", "Le Port", "Saint-Louis", "Sainte-Marie",
  "Sainte-Suzanne", "Basse-Terre", "Les Abymes", "Baie-Mahault", "Le Gosier", "Sainte-Anne",
  "Morne-à-l'Eau", "Petit-Bourg", "Lamentin", "Matoury", "Remire-Montjoly", "Kourou", "Marigot",
  "Dzaoudzi", "Koungou", "Dembeni", "Pamandzi", "Bandraboua", "Acoua", "Tsingoni",
].sort();

export const frenchCountries = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Birmanie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo",
  "Corée du Nord",
  "Corée du Sud",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "Eswatini",
  "États-Unis",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée équatoriale",
  "Guinée-Bissau",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Kosovo",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Liberia",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine du Nord",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "République centrafricaine",
  "République démocratique du Congo",
  "République dominicaine",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Christophe-et-Niévès",
  "Sainte-Lucie",
  "Saint-Marin",
  "Saint-Vincent-et-les-Grenadines",
  "Salomon",
  "Salvador",
  "Samoa",
  "São Tomé-et-Príncipe",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Yémen",
  "Zambie",
  "Zimbabwe",
].sort();
